### ISSUE TITLE
Couldn't start client Phpactor Language Server

### ISSUE THREAD

**Issue by ctf0** [phpactor/vscode-phpactor#114]
recently i started getting this error when running the app via docker, i have this config which is the same for `php.validate.executablePath`
```json
"phpactor.executablePath": "/usr/local/bin/docker exec user-demo-laravel.test-1 php",
```

- console log error
```console
Couldn't start client Phpactor Language Server
c @ notificationsAlerts.ts:42
log.ts:439   ERR spawn /usr/local/bin/docker exec user-demo-laravel.test-1 php ENOENT: Error: spawn /usr/local/bin/docker exec user-demo-laravel.test-1 php ENOENT
    at Process.ChildProcess._handle.onexit (node:internal/child_process:284:19)
    at onErrorNT (node:internal/child_process:477:16)
    at processTicksAndRejections (node:internal/process/task_queues:82:21)
```

- vscode logger error
```log
[Error - 6:59:35 PM] Starting client failed
Launching server using command /usr/local/bin/docker exec user-demo-laravel.test-1 php failed.
```

is there away to get phpactor to work correctly with docker ?

**Comment by ctf0** [comment]
> Your IDE and PhpActor will run inside the container and this works great

can u share the steps to do so ?

on the other hand, why the extension doesnt use the php executable path i gave to run all its code like normal ?

**Comment by zobo** [comment]
Because it's not an executable but an executable with arguments. 

I suggest to start here https://code.visualstudio.com/docs/devcontainers/containers

Just install vscode remote comtainer extension and attach to your running docker. Then install phpactor extension inside the docker.

**Comment by ctf0** [comment]
ok, i did that but honestly thats too much work because
- now i have to install phpactor as a composer dep of the project
- any custom config files, needs to be copied to the project

there must be another easier/smoother way to use the extension with docker through config instead of a custom setup.
