### ISSUE TITLE
vs code extension is not working

### ISSUE THREAD

**Issue by DhiaBen20** [phpactor/vscode-phpactor#115]
I am getting this error after installing the vs code extension even  though i installed phpactor and added it to my `path`

```
[Error - 3:21:39 AM] Starting client failed
Launching server using command php failed.
```

**Comment by zobo** [comment]
The latest version of vscode-phpactor comes bundeled with phpactor phar. It tries to run `php (path to extension data)/phpactor.phar`.

The error indicates that perhaps vscode was not able to find PHP in the path. These are the steps that the extension makes to resolve path to php
- setting `phpactor.executablePath`
- setting `php.executablePath`
- setting `php.validate.executablePath`
- `php`

First one set is used. If you have php in a special location and not in path, add the setting `phpactor.execuablePath`.

Try to also set verbose logging via setting `phpactor.trace.server` to see if there is any other logs available.

**Comment by DhiaBen20** [comment]
I encountered this issue on Pop!_OS, and it wasn't just this particular problem. PHP CS Fixer didn't work either, and every time I opened a PHP file, VS Code would prompt me to set `php.validate.executablePath`, which was quite strange. So, I decided to delete Pop!_OS and installed Debian instead, and now everything works fine.
