### ISSUE TITLE
Publish to Open VSX

### ISSUE THREAD

**Issue by assyrus-favolo** [phpactor/vscode-phpactor#118]
Hi!
I'm confused as to why the discussion on publishing to Open VSX fizzled out on #40, it's a marketplace used by [several applications now](https://open-vsx.org/adopters), on top of VSCodium (which is where I would like to install this), could you reconsider it?

**Comment by zobo** [comment]
Sorry, will check it out and publish this version

**Comment by assyrus-favolo** [comment]
Thanks a lot!! And no need to be sorry, I was just curious :)

**Comment by assyrus-favolo** [comment]
Sorry, I forgot to check back.  
I thought I couldn't try it at first today because I noticed that phpactor doesn't support Windows yet, but just for the sake of trying I was actually able to run it from within WSL and connecting to it remotely through [Open Remote - WSL](https://open-vsx.org/extension/jeanp413/open-remote-wsl) and it's working fine as far as I can tell, thanks again!!
