### ISSUE TITLE
Diagnostic provider "outsourced" error & develop branch no longer maintained notification

### ISSUE THREAD

**Issue by kachidk** [phpactor/vscode-phpactor#119]
Hello,

Whenever I restart VSCode and open a PHP file I get this notification.

Plugin version: 1.3.0
OS: macOS
VSCode version: 1.85.2

<img width="487" alt="image" src="https://github.com/phpactor/vscode-phpactor/assets/61981167/e8e81ae8-be47-49a4-9dce-848bbe90bfd3">

**Comment by zobo** [comment]
The "outsourced" error is known and I have yet to get to this: https://github.com/phpactor/vscode-phpactor/issues/113
The other message indicates your are not using the bundled phpactor phar but rather something on your disk probably configured via `phpactor.path` setting. Either remove that or manually git switch and update your checked out phpactor source. Also don't forget to composer install after update.

**Comment by kachidk** [comment]
>The other message indicates your are not using the bundled phpactor phar but rather something on your disk probably configured via phpactor.path setting.

Nothing is configured with the `phpactor.path` setting. I don't have phpactor installed globally because I want to use the `phpactor.phar` bundled with the extension.

Please how do I do this:

>Either remove that or manually git switch and update your checked out phpactor source. Also don't forget to composer install after update.

---

Info after running `Phpactor: Show current status`

```
Process
-------

  cwd:/Users/ABC/Projects/monorepo-api
  pid: 33577
  up: 0d 0h 18m 38s

Server
------

  mem: 72,427,216b
  documents: 0
  services: ["diagnostics","serviceAnnouncements","indexer"]
  diagnostics: outsourced, php-lint

Paths
-----

  project_id: monorepo-api-abcde
  project_root: /Users/ABC/Projects/monorepo-api
  cache: /Users/ABC/.cache/phpactor
  config: /Users/ABC/.config/phpactor
  data: /Users/ABC/.local/share/phpactor
  application_root: phar:///Users/ABC/.vscode/extensions/phpactor.vscode-phpactor-1.3.0/phpactor.phar
  project_config: /Users/ABC/Projects/monorepo-api/.phpactor

Indexer
-------

  watcher: pattern matching LSP file events
```

**Comment by kachidk** [comment]
I solved it by restarting my system. I guess it must have stopped the old process.

**Comment by kachidk** [comment]
I solved it by restarting my system. I guess it must have stopped the old process.
