### ISSUE TITLE
Significant delay on large projects

### ISSUE THREAD

**Issue by BladeMF** [phpactor/vscode-phpactor#12]
In a mid-sized Symfony project there is a consistent ~3 second delay before type information and intellisense are displayed.

**Comment by dantleech** [comment]
hmm, in a 26k file project it's almost instant for me. You might check the logs and see which "source locator" is being used - as one thing that can slow down Phpactor considerably is if it's scanning the filesystem instead of using the Index or Composer to locate files.

**Comment by BladeMF** [comment]
It says "Running services - diagnostics, indexer" I am seeing a bunch of find calls in the log.

**Comment by BladeMF** [comment]
The delay is NOT caused by the CompletionHandler::completion, I timed it, it costs 0.0011225368976593 from the call of the method to the completion of the `Promise`.

Here is a video of the delay, you may see something I've missed:

![AppExtension php - ideasPlatform  WSL_ CT2  - Visual Studio Code 2020-12-14 11-14-52](https://user-images.githubusercontent.com/12109622/102063260-75aa1380-3dfe-11eb-8fb4-72c119d619d4.gif)

**Comment by BladeMF** [comment]
You see the completion list twice because I have a second language server running (it doesn't affect it). Also, commenting the completion method like so...
```php
    public function completion(CompletionParams $params, CancellationToken $token): Promise
    {
        // $start = microtime(true);
        return \Amp\call(function () use ($params, $token, $start) {
            $check1 = (microtime(true) - $start) /  1000;
            $textDocument = $this->workspace->get($params->textDocument->uri);

            $languageId = $textDocument->languageId ?: 'php';
            $byteOffset = PositionConverter::positionToByteOffset($params->position, $textDocument->text);
            
            // $suggestions = $this->registry->completorForType(
            //     $languageId
            // )->complete(
            //     TextDocumentBuilder::create($textDocument->text)->language($languageId)->uri($textDocument->uri)->build(),
            //     $byteOffset
            // );

            $items = [];
            $isIncomplete = false;
            // foreach ($suggestions as $suggestion) {
            //     $name = $this->suggestionNameFormatter->format($suggestion);
            //     $insertText = $name;
            //     $insertTextFormat = InsertTextFormat::PLAIN_TEXT;

            //     if ($this->supportSnippets) {
            //         $insertText = $suggestion->snippet() ?: $name;
            //         $insertTextFormat = $suggestion->snippet()
            //             ? InsertTextFormat::SNIPPET
            //             : InsertTextFormat::PLAIN_TEXT
            //         ;
            //     }

            //     $items[] = CompletionItem::fromArray([
            //         'label' => $name,
            //         'kind' => PhpactorToLspCompletionType::fromPhpactorType($suggestion->type()),
            //         'detail' => $this->formatShortDescription($suggestion),
            //         'documentation' => $suggestion->documentation(),
            //         'insertText' => $insertText,
            //         'textEdit' => $this->textEdit($suggestion, $textDocument),
            //         'command' => $this->command($textDocument->uri, $byteOffset, $suggestion),
            //         'insertTextFormat' => $insertTextFormat
            //     ]);

            //     try {
            //         $token->throwIfRequested();
            //     } catch (CancelledException $cancellation) {
            //         $isIncomplete = true;
            //         break;
            //     }
            //     yield new Delayed(0);
            // }

            // $isIncomplete = $isIncomplete || !$suggestions->getReturn();

            $list = new CompletionList($isIncomplete, $items);
            $end = ((microtime(true) - $start)/1000);
            file_put_contents("/root/completions.log", "Check1: $check1; End: $end\n\n", FILE_APPEND);
            return $list;
        });
    }
```
... removes the delay. You can see my timing code there also. It's probably my lack of knowledge that's preventing me to see the reason. I hope you see it.

**Comment by dantleech** [comment]
hnmm, but you already said `The delay is NOT caused by the CompletionHandler::completion`?

I would look at the lines such as:

```
phpactor.DEBUG: NOK [0.0000] "Foo\Bundle\StoreBundle\Shipping\assert" with locator "Phpactor\Extension\LanguageServerWorseReflection\SourceLocator\WorkspaceSourceLocator" : Class "Reiss\Bundle\StoreBundle\Shipping\assert" not found
```

int he logs and see if the language server stalls on any one of those

**Comment by BladeMF** [comment]
> hnmm, but you already said The delay is NOT caused by the CompletionHandler::completion?

I know! Comment the code - it is fast. Uncomment the code - it is slow.

There is the log - the only thing in it is one startup and one `$this->`. 3k lines - [phpactor-session.txt](https://github.com/phpactor/vscode-phpactor/files/5688008/phpactor-session.txt)

**Comment by BladeMF** [comment]
The logs are still triggered when the code is commented out. It's the not the completion that is the problem. When I don't type and just hit Ctrl+Space it takes around a second - still slower than the other extension that I use, but _a lot better_, and there are no logs being produced. It's the typing that's producing the delay I think. Probably when I comment out the code VS Code knows the empty list and shows the default completion list instantly.
