### ISSUE TITLE
Implement textDocument/prepareRename and textDocument/rename

### ISSUE THREAD

**Issue by BladeMF** [phpactor/vscode-phpactor#21]
Implementing the rename functionality with proper edits so it can be undone. 
I am opening this issue so we can discuss here.

**Comment by BladeMF** [comment]
I am successfully renaming classes, methods and properties.

**Comment by BladeMF** [comment]
So, here are my current issues with this (the code is [here](https://github.com/BladeMF/language-server-phpactor-extensions/tree/try-actions/lib/LanguageServerRename)):

#### There are literally no tests
I need help with how I can create a test setup in which the `ReferenceFinder` and the `DefinitionLocator` will return actual results so I can test my code with those.

#### ReferenceFinder
It seems to have issue with static properties as it doesn't find them. Haven't looked into it yet.

#### Renaming variables
That is not implemented. It would seem I need to use `TolerantRenameVariable` and then convert the `Phpactor\TextDocument\TextEdit` to its LSP counterpart, right? That appears to be true for most transforms in `Phpactor\Extension\CodeTransformExtra\Rpc`, am I correct?

In that line of thought, probably what I've written should be moved in the `code_transofrm` package and changed to use the local abstractions, right?

#### The code

The way renames are allowed and disallowed is by examining the nodes types. It feels repetitive and smells of a lot of things, but then I was more focused on getting it to work.

The code is not `yield`ing. Probably the structure of the `Renamer::renameClassOrMemberSymbol` is dumb, I need to think about it. Probably the reason is that I started with the code in `ReferencesHandler` and it took a while to get comfortable with all the concepts. I need a while to think.

_(The index)_
You said:

> it should probably be re-written to use the indexer in the LS

I am not sure what you meant as I didn't have to use an indexer.

---
That is it for now.

**Comment by BladeMF** [comment]
Tried to implement `TolerantRenameVariable` and had trouble with `TextEditBulder` when renames are on neighbouring lines:

#### Original source
```php
<?php
declare(strict_types=1);

namespace Temp2\Folder;

class Class3
{
	public function func1(): void
	{
		$var1 = 5;
		$var1++;
	}
}
```

#### After calculating edits
`$edits = $this->textEditBuilder->calculateTextEdits((string)$phpactorDocument, $newSource);`
The first two overlap:
```
array:4 [
  0 => array:3 [
    "start" => array:2 [
      "line" => 9
      "character" => 0
    ]
    "end" => array:2 [
      "line" => 10
      "character" => 0
    ]
    "text" => ""
  ]
  1 => array:3 [
    "start" => array:2 [
      "line" => 9
      "character" => 0
    ]
    "end" => array:2 [
      "line" => 10
      "character" => 0
    ]
    "text" => ""
  ]
  2 => array:3 [
    "start" => array:2 [
      "line" => 9
      "character" => 0
    ]
    "end" => array:2 [
      "line" => 9
      "character" => 0
    ]
    "text" => "\t\t$var12 = 5;\n"
  ]
  3 => array:3 [
    "start" => array:2 [
      "line" => 10
      "character" => 0
    ]
    "end" => array:2 [
      "line" => 10
      "character" => 0
    ]
    "text" => "\t\t$var12++;\n"
  ]
]
```

**Comment by BladeMF** [comment]
Seems kind of a waste calculating the proper edits, then returning fixed source, then calculating the edits again? Should we split this service into 2 - one that calculates the edits, and another which implements the interface which returns the final source code?

**Comment by dantleech** [comment]
Please open a PR :) There are lots of questions here and I'm finding it difficult to process them, we should focus on a single thing, e.g. renaming local variables using the existing functionality is a good start.

in the long run:

- the handler should delegate the renaming based on the node type.
- renamed classes need to have their files renamed.
- searching for method usage will often take an extremely long time because it needs to statically analyse the file to see which class it belongs to - it needs to be optimised.

but one thing at a time

**Comment by BladeMF** [comment]
I will, once I am happy with my code, because it was the first thing that I wrote and it is kind of ugly. For the variable renaming I was forced to replace the whole file for it to work for now.

> the handler should delegate the renaming based on the node type.

Since I use the reference finder, there are only two cases - references and variables. You'll see the code once I create the PR.

> renamed classes need to have their files renamed.

Probably only if they are the first class in the file?

I think the only immediate thing to solve is how to write my test cases. If Uncle Bob finds out, I'm in big trouble, man. I'll probably be grounded! 😂🤣😂🤣

**Comment by BladeMF** [comment]
> renamed classes need to have their files renamed.

Rename file only if old name matches fil name, right?

> searching for method usage will often take an extremely long time because it needs to statically analyse the file to see which class it belongs to - it needs to be optimised.

That's `WorseReflection`'s enhancing, right?

**Comment by dantleech** [comment]
> Rename file only if old name matches fil name, right?

Yes

> That's WorseReflection's enhancing, right?

Basically. But that will often time out - the existing algorithm will brute force it's way through (and may be more optimised)

---

It also needs to update all the `use` statements in the code

**Comment by dantleech** [comment]
> will brute force it's way through (and may be more optimised)

ah - the existing one will only search the files in GIT - so doesn't scan the `vendor` and that is _much_ faster.

**Comment by BladeMF** [comment]
> It also needs to update all the use statements in the code

I think that gets renamed... Will double-check.

**Comment by BladeMF** [comment]
Rename files for:
* Classes
* Interfaces
* Traits

Anything else?

**Comment by dantleech** [comment]
That's all AFAIK

**Comment by BladeMF** [comment]
Rename is working for classes and interfaces, have missed traits completely. ☺

**Comment by BladeMF** [comment]
Try to guess if Find all references finds use cases 😂🤣 Oh man, just when I think about submitting....

**Comment by BladeMF** [comment]
https://github.com/phpactor/phpactor/issues/1162
