### ISSUE TITLE
The commands are missing

### ISSUE THREAD

**Issue by BladeMF** [phpactor/vscode-phpactor#4]
I can't find the commands, mentioned in the README:

![image](https://user-images.githubusercontent.com/12109622/102010535-5308f380-3d47-11eb-9d65-2b29f41d7750.png)

**Comment by dantleech** [comment]
While the commands are [registered](https://github.com/phpactor/vscode-phpactor/blob/master/src/extension.ts#L56) I think they need to be configured in `package.json` to be available from the UI:

https://code.visualstudio.com/api/extension-guides/command#creating-a-user-facing-command

**Comment by BladeMF** [comment]
I'll have a play when I have time.

**Comment by BladeMF** [comment]
Pull request incoming.
