### ISSUE TITLE
parser doesnt count for docblock

### ISSUE THREAD

**Issue by ctf0** [phpactor/vscode-phpactor#45]
```
/**
 * Determine if the user is authorized to make this request.
 *
 * @return bool
 */
public function authorize()
{
    return true;
}
```

![Screen Shot 2023-01-09 at 5 59 44 AM](https://user-images.githubusercontent.com/7388088/211239060-7432ad99-fdb0-45d7-86ab-3b6b36d06af0.png)

**Comment by dantleech** [comment]
This is as designed, you are missing the actual return type, specifying it as a docblock isn't necessary?

**Comment by ctf0** [comment]
am probably missing something, but the method & its doc are correct, using a php 8 return type hint or using docblock should be treated the same.

**Comment by dantleech** [comment]
you can still add a return type even if it's FW logic - is there a reason not to?

but open having a config option to surpress this if the docblock is set

**Comment by ctf0** [comment]
believe it or not, the parser actually count for docblocks 

- `/Users/xxx/.composer/vendor/twig/twig/src/Loader/ChainLoader.php#83`

![Screen Shot 2023-01-09 at 11 32 34 AM](https://user-images.githubusercontent.com/7388088/211277833-c3b33245-fdb3-4a52-8d8b-875afa60cf12.png)

in this case it should have complained about native type hints instead, or is it a different issue ?

**Comment by dantleech** [comment]
the diagnostic above is saying that there is no type information (native or docblock) for `$name`, I'd expect there to additionally be a warning about not having a return type.

**Comment by ctf0** [comment]
true
