### ISSUE TITLE
$this autocompletion

### ISSUE THREAD

**Issue by BladeMF** [phpactor/vscode-phpactor#5]
When I type `$th` and then hit `Tab`, I get this:

![image](https://user-images.githubusercontent.com/12109622/102011017-55208180-3d4a-11eb-9d63-0418ae52c396.png)

**Comment by dantleech** [comment]
This is a known issue:

https://phpactor.readthedocs.io/en/develop/lsp/vim.html#two-dollars-on-variables

Note that we should probably switch the default value here,.

**Comment by dantleech** [comment]
In vs. code I guess you should be able to add the above referenced configuration in a/the `phpactor` section.

**Comment by BladeMF** [comment]
Yes, I just tried it and it works. Thank you.
