### ISSUE TITLE
Problems with static methods

### ISSUE THREAD

**Issue by BladeMF** [phpactor/vscode-phpactor#6]
When there are static methods in class, I get the following behavior:

here's the class:
![image](https://user-images.githubusercontent.com/12109622/102011042-76816d80-3d4a-11eb-8ee8-23404a193031.png)

When I type `self::`, the method is missing:
![image](https://user-images.githubusercontent.com/12109622/102011051-81d49900-3d4a-11eb-9bec-7e7a90b7fc5e.png)

When I type then `self::s`, the method appears:
![image](https://user-images.githubusercontent.com/12109622/102011057-8d27c480-3d4a-11eb-90a9-a9853a212100.png)

When I autocomplete it and then try to show the signature tooltip, it does not appear, like it does for other methods:
![image](https://user-images.githubusercontent.com/12109622/102011069-a761a280-3d4a-11eb-894a-d148ae3165c2.png)
(it should be:)
![image](https://user-images.githubusercontent.com/12109622/102011304-f65c0780-3d4b-11eb-9671-e4ed80865ca8.png)

**Comment by dantleech** [comment]
Indeed - `static` seems to not resolve to the current class, `self::` does I think.

**Comment by BladeMF** [comment]
Nope, same behavior:
![image](https://user-images.githubusercontent.com/12109622/102011523-5e5f1d80-3d4d-11eb-9ef0-8f3a1f356420.png)
![image](https://user-images.githubusercontent.com/12109622/102011527-64ed9500-3d4d-11eb-8a6d-a857c7b4e39b.png)
![image](https://user-images.githubusercontent.com/12109622/102011530-6d45d000-3d4d-11eb-8cbc-5510726e0cf9.png)

**Comment by dantleech** [comment]
It's very strange that you are seeing PHPUnit completions for that class? Are you sure they are coming from Phpactor?

**Comment by BladeMF** [comment]
No, I wouldn't bet they are. I just showed how there were no completions for the method. I think I have installed some extensions that have snippets for PHPUnit. I think you should ignore the other visible stuff.

**Comment by dantleech** [comment]
So:

- If I create a new file in an empty directory: Phpactor does not detect the file and any contents in it is not found.
- If I reload the file Phpactor detects it fine

Note that in general Phpactor works better in a standard PHP setup with a `composer` autoloader.

**Comment by BladeMF** [comment]
This behaviour is not changed when you reload. Did you mean to write in the other issue?

> Note that in general Phpactor works better in a standard PHP setup with a composer autoloader.

Noted. I just created an empty workspace so I can test it. My usual projects are Symfony stuff.
