### ISSUE TITLE
Coding standards and editor.config

### ISSUE THREAD

**Issue by BladeMF** [phpactor/vscode-phpactor#9]
I forked this with the intention of contributing stuff when I have the time, but the first pull request failed to merge properly - it removed the entire file and then re-added it, which I think is due to whitespace and line ending issues. So (_sorry, I am new to this_):

1. What line ending should I use?
2. What indentation - type and width?
3. Can I create an editor.config so it kinda comes with the repo?
4. ~~What should I do about the .vscode folder (it has a local config in there and tasks that can be executed)?~~ Sorry, I just saw it is already ignored.

Thanks for your help.

**Comment by dantleech** [comment]
> first pull request failed to merge properly - it removed the entire file and then re-added it
not sure what you mean here -- which pull request?

---


>  What line ending should I use?

`\n` is standard (even on Windows now) I think.

> What indentation - type and width?

Generally 2 spaces no tabs (I think this is what this repo uses)

> Can I create an editor.config so it kinda comes with the repo?

Sure

> What should I do about the .vscode folder (it has a local config in there and tasks that can be executed)?

You can add it to the `.gitignore` file

**Comment by BladeMF** [comment]
> Generally 2 spaces no tabs (I think this is what this repo uses)

The files seem to have 4.

**Comment by dantleech** [comment]
Then 4 :) I copied this code from other VSCode extensions, so that's probably the standard there.

**Comment by BladeMF** [comment]
Agreed. It's your repo - it's whatever you say.
